### ISSUE TITLE
Support 2.13

### ISSUE THREAD

**Issue by aginiewicz** [rtimush/scalatags-rx#13]
Hi! Do you have some roadmap for 2.13 support? Thanks!

**Comment by rtimush** [comment]
Hi @aginiewicz. I don't have any roadmap, but I will take a look if it's easy to upgrade. If someone makes a PR, I will be also happy to merge it.

**Comment by aginiewicz** [comment]
Hi were you looking into this issue by any chance? Seems simon-morgan did some work in his fork https://github.com/simon-morgan/scalatags-rx :)

**Comment by aginiewicz** [comment]
Wonderful news! Looking forward to a release :)

Thanks for great work on this project!

**Comment by rtimush** [comment]
Hi @aginiewicz, I published 0.5.0. Sorry for a long wait.

**Comment by aginiewicz** [comment]
Thanks!
