### ISSUE TITLE
Publish newer releases to Maven

### ISSUE THREAD

**Issue by drhumlen** [rtimush/scalatags-rx#7]
Over at maven central, the newest version is still 0.1 ( http://search.maven.org/#search%7Cga%7C1%7Cscalatags-rx ). Perhaps you could publish the newer versions so that it's easy for new projects to depend on `scalatags-rx`? 

It's an awesome library; and the missing link between scalatags and rx. It really takes things to the next level. It's like the ELK stack - it's when you combine the three that things get interesting.

Also, could you have a look at my PR (and publish it if it looks good)? Thanks
https://github.com/rtimush/scalatags-rx/pull/6

**Comment by vaclavsvejcar** [comment]
@rtimush Just want to ask about the state of this issue, do you plan to publish new versions in near future? I'd be awesome to see release 0.3.1 with #6 pull request merged. 😄

**Comment by rtimush** [comment]
The new version published to maven central (it is actually 0.3.0, not 0.3.1).

**Comment by vaclavsvejcar** [comment]
Hi @rtimush, I'm still having trouble to use version 0.3.0 you mentioned as a dependency, SBT complaints that it cannot be resolved

```
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/timushev/scalatags-rx_sjs0.6_2.11/0.3.0/scalatags-rx_sjs0.6_2.11-0.3.0.pom
```

and I even cannot find it manually in Maven central. Can you please check this out?

**Comment by rtimush** [comment]
@vaclavsvejcar thank you, forgot to actually release from the sonatype staging. Should be available in Maven Central shortly.

**Comment by vaclavsvejcar** [comment]
@rtimush awesome, works now, thank you
